### ISSUE TITLE
Takedown request

### ISSUE THREAD

**Issue by meronig** [MatJorgensen/02393-programming-in-cpp#1]
Dear maintainer,
We are contacting you since we are the course responsible for 02393 Programming in C++ at DTU, and we noticed that you published the solutions to all the weekly assignments and past exams for that course on this GitHub repository.

We believe that making the solutions immediately accessible to students would harm their learning experience, as current students may be tempted to simply use the solutions in your repository to pass the weekly assignments, without understanding how to implement a solution on their own. This, in turn, could cause them not to properly prepare for the final exam, thus failing it.

Therefore, we kindly ask you to take this repository down.

Thanks for your cooperation.

Alceste Scalas and Giovanni Meroni, course responsibles for 02393 Programming in C++ at DTU.

**Comment by MatJorgensen** [comment]
No worries. I'll take down the repo. 😊
